#!/usr/bin/env node
/**
 * Writes life-os/.env.local from environment secrets (does not print secret values).
 */
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

const required = [
  "NEXT_PUBLIC_SUPABASE_URL",
  "NEXT_PUBLIC_SUPABASE_ANON_KEY",
];

const missing = required.filter((k) => !process.env[k]);
if (missing.length) {
  console.error("Missing:", missing.join(", "));
  process.exit(1);
}

const lines = [
  "# Generated by scripts/write-env.mjs — do not commit",
  `NEXT_PUBLIC_SUPABASE_URL=${process.env.NEXT_PUBLIC_SUPABASE_URL}`,
  `NEXT_PUBLIC_SUPABASE_ANON_KEY=${process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY}`,
];

if (process.env.GEMINI_API_KEY) {
  lines.push(`GEMINI_API_KEY=${process.env.GEMINI_API_KEY}`);
}
if (process.env.SUPABASE_ACCESS_TOKEN) {
  lines.push(`SUPABASE_ACCESS_TOKEN=${process.env.SUPABASE_ACCESS_TOKEN}`);
}

const out = resolve(root, ".env.local");
writeFileSync(out, lines.join("\n") + "\n", { mode: 0o600 });
console.log("Wrote .env.local with:", lines.map((l) => l.split("=")[0]).join(", "));
