#!/usr/bin/env node
/**
 * Writes life-os/.env.local from environment secrets (does not print secret values).
 */
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { resolveSupabaseUrl } from "./supabase-env.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

const url = resolveSupabaseUrl();
const anon = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY?.trim();

if (!url) {
  console.error(
    "Missing project id/url. Set SUPABASE_PROJECT_ID or NEXT_PUBLIC_SUPABASE_URL.",
  );
  process.exit(1);
}
if (!anon) {
  console.error("Missing NEXT_PUBLIC_SUPABASE_ANON_KEY (publishable key).");
  process.exit(1);
}

const lines = [
  "# Generated by scripts/write-env.mjs — do not commit",
  `NEXT_PUBLIC_SUPABASE_URL=${url}`,
  `NEXT_PUBLIC_SUPABASE_ANON_KEY=${anon}`,
];

for (const key of [
  "SUPABASE_SECRET_KEY",
  "SUPABASE_PROJECT_ID",
  "DATABASE_URL",
  "GEMINI_API_KEY",
  "SUPABASE_ACCESS_TOKEN",
]) {
  if (process.env[key]) lines.push(`${key}=${process.env[key]}`);
}

const out = resolve(root, ".env.local");
writeFileSync(out, lines.join("\n") + "\n", { mode: 0o600 });
console.log(
  "Wrote .env.local with:",
  lines.map((l) => l.split("=")[0]).join(", "),
);
console.log("Resolved URL host:", new URL(url).host);
