export type DriverStats = {
  driving: number;
  speed: number;
  handling: number;
  consistency: number;
  aggression: number;
  luck: number;
};

export type Driver = {
  id: string;
  name: string;
  nickname: string;
  number: string;
  slug: string;
  image: string;
  tagline: string;
  bio: string;
  catchphrase: string;
  signature: string;
  strength: string;
  funFact: string;
  credentials: string[];
  sponsors: string[];
  lines: string[];
  rival: string;
  careerWins: number;
  stats: DriverStats;
  isLegendary?: boolean;
  accent: string;
};

export const DRIVERS: Driver[] = [
  {
    id: "grammy",
    name: "Grammy",
    nickname: "The Grand Marshal",
    number: "99",
    slug: "grammy",
    image: "/drivers/grammy.png",
    tagline: "The field races for second.",
    bio: "She doesn’t enter the weekend. The weekend enters her orbit. When Grammy rolls to the line, the Solo cups straighten up on their own. The $500 isn’t a prize — it’s pilgrimage money. Careers are measured in seasons. Hers is measured in eras.",
    catchphrase: "Come give Grammy a hug… after she lapped you.",
    signature: "The Coral Crown — late apex, early celebration",
    strength: "Divine authority · Impossible pace · Crowd worship",
    funFact: "Crowd favorite and betting favorite — rare in nature. Allegedly undefeated in hotel hallways.",
    credentials: [
      "47 career wins across patios, beaches & one alleged hallway",
      "Honorary Race Control veto",
      "Patron Saint of the Solo Cup",
      "Status: IMMORTAL",
    ],
    sponsors: ["Divine Timing Co.", "Golden Foil Athletics", "Hugs & Horsepower"],
    lines: [
      "Loading Grammy… please remain standing.",
      "Opponents don’t lose. They get blessed with perspective.",
      "Solo cups are red. Legends are gold.",
      "47 wins. Zero equals. One crown.",
      "$500 is not a prize. It’s tribute.",
    ],
    rival: "n/a — gods don’t schedule rivals",
    careerWins: 47,
    stats: {
      driving: 99,
      speed: 98,
      handling: 99,
      consistency: 99,
      aggression: 85,
      luck: 100,
    },
    isLegendary: true,
    accent: "#f5d76e",
  },
  {
    id: "hap",
    name: "Hap",
    nickname: "Happy Hour",
    number: "07",
    slug: "hap",
    image: "/drivers/hap.png",
    tagline: "Green flag? Great flag.",
    bio: "Hap brings the vibe and the pace. Always smiling, always ready for one more heat, always the guy who makes the pits feel like a party — then quietly parks it up front.",
    catchphrase: "Green flag? Great flag.",
    signature: "The Good Times Gap",
    strength: "Morale + momentum",
    funFact: "Has never met a warm-up he didn’t love.",
    credentials: ["Most likely to turn a practice lap into a memory", "Pit-lane hype captain"],
    sponsors: ["Sunset Sip Energy", "Coral Grip"],
    lines: ["One more heat!", "We’re already having fun — might as well win."],
    rival: "Ben (friendly fire)",
    careerWins: 5,
    stats: {
      driving: 90,
      speed: 84,
      handling: 82,
      consistency: 86,
      aggression: 62,
      luck: 76,
    },
    accent: "#f59e0b",
  },
  {
    id: "ben",
    name: "Ben",
    nickname: "Bounceback",
    number: "23",
    slug: "ben",
    image: "/drivers/ben.png",
    tagline: "Reset. Relight. Remax.",
    bio: "Ben’s the comeback main character. Clip a cup? He’s already resetting. Bad heat? He’s hunting the next one like it owes him ice cream. Cool under pressure, louder when it counts, built for second-chance glory.",
    catchphrase: "Reset. Relight. Remax.",
    signature: "Phoenix Pass — charges back after drama",
    strength: "Clutch recovery · Main-character energy",
    funFact: "Practices victory nods in reflective surfaces.",
    credentials: ["Comeback Merchant", "Crowd riser", "Unofficial hype DJ of the pits"],
    sponsors: ["Second Wind Supply Co.", "Teal Torque"],
    lines: [
      "Pressure’s just another green flag.",
      "I don’t stay down. I reload.",
      "That wasn’t a mistake — that was foreshadowing.",
    ],
    rival: "Tripp / Logan — all smiles",
    careerWins: 3,
    stats: {
      driving: 88,
      speed: 86,
      handling: 74,
      consistency: 72,
      aggression: 78,
      luck: 70,
    },
    accent: "#22d3ee",
  },
  {
    id: "logan",
    name: "Logan",
    nickname: "Lowkey",
    number: "27",
    slug: "logan",
    image: "/drivers/logan.png",
    tagline: "…then a podium.",
    bio: "Doesn’t say much. Doesn’t need to. Logan’s card looks calm until the timesheets show up and everyone’s like, oh.",
    catchphrase: "…",
    signature: "Silent Gap",
    strength: "Consistency under island heat",
    funFact: "Saves all his words for after the checkered.",
    credentials: ["Dark horse with good posture", "Quiet Speed certified"],
    sponsors: ["Quiet Speed Ltd.", "Horizon Calm Racing"],
    lines: ["Results talk.", "Still water. Fast water."],
    rival: "Abby (precision wars)",
    careerWins: 3,
    stats: {
      driving: 87,
      speed: 80,
      handling: 86,
      consistency: 90,
      aggression: 52,
      luck: 75,
    },
    accent: "#64748b",
  },
  {
    id: "tripp",
    name: "Tripp",
    nickname: "Trapdoor",
    number: "44",
    slug: "tripp",
    image: "/drivers/tripp.png",
    tagline: "Vacation mode: competitive.",
    bio: "Named for the trip and the vibes. Tripp looks friendly at the start line, then drops a lap that makes the leaderboard do a double take.",
    catchphrase: "Vacation mode: competitive.",
    signature: "Trapdoor Draft — gone from mirrors, back in P1",
    strength: "Surprise pace",
    funFact: "Treats every heat like a postcard he’ll brag about later.",
    credentials: ["Sideways-optional, smiles-mandatory", "Island Momentum alum"],
    sponsors: ["Island Momentum", "Flamingo Fuel"],
    lines: ["Look safe. Ben’t.", "Postcard pace."],
    rival: "Ben",
    careerWins: 2,
    stats: {
      driving: 86,
      speed: 90,
      handling: 72,
      consistency: 66,
      aggression: 82,
      luck: 78,
    },
    accent: "#fb7185",
  },
  {
    id: "parker",
    name: "Parker",
    nickname: "Park It",
    number: "33",
    slug: "parker",
    image: "/drivers/parker.png",
    tagline: "Commit to the bit.",
    bio: "Parker races with style and commitment — sometimes to the racing line, sometimes to a scenic detour that somehow still works. Cool either way.",
    catchphrase: "Commit to the bit.",
    signature: "Scenic Attack",
    strength: "Adaptability",
    funFact: "Could find grip on a towel.",
    credentials: ["Most creative racing line in Aruba (self-awarded, widely respected)"],
    sponsors: ["Detour Athletic", "Beach Blanket Racing"],
    lines: ["Scenic doesn’t mean slow.", "Commit."],
    rival: "Parker vs. the layout",
    careerWins: 2,
    stats: {
      driving: 85,
      speed: 81,
      handling: 76,
      consistency: 70,
      aggression: 64,
      luck: 72,
    },
    accent: "#a78bfa",
  },
  {
    id: "jude",
    name: "Jude",
    nickname: "Judgment Day",
    number: "09",
    slug: "jude",
    image: "/drivers/jude.png",
    tagline: "It’s a heat. Treat it like one.",
    bio: "Jude brings finals energy even to warm-ups. Card stats sit mid-pack; attitude says main event. Cool, locked in, ready for the moment.",
    catchphrase: "It’s a heat. Treat it like one.",
    signature: "Late Charge",
    strength: "Big-moment focus",
    funFact: "Practices podium handshakes — optimistic and adorable.",
    credentials: ["Clutch curiosity", "Mini-prize believer"],
    sponsors: ["Late Apex Co.", "SoloSeal"],
    lines: ["Treat warm-ups like finals.", "Moment incoming."],
    rival: "Whoever’s ahead on the last lap",
    careerWins: 1,
    stats: {
      driving: 78,
      speed: 76,
      handling: 74,
      consistency: 72,
      aggression: 68,
      luck: 65,
    },
    accent: "#38bdf8",
  },
  {
    id: "sue",
    name: "Sue",
    nickname: "Steel Pedal",
    number: "01",
    slug: "sue",
    image: "/drivers/sue.png",
    tagline: "Nice and tidy.",
    bio: "Smooth, steady, quietly dangerous. Sue doesn’t need chaos — she needs a clean line and a fair shot. When she’s on, the cups look nervous for aesthetic reasons only.",
    catchphrase: "Nice and tidy.",
    signature: "The Quiet Pass",
    strength: "Composure under beach pressure",
    funFact: "Can spot a crooked gate from across the courtyard.",
    credentials: ['Unofficial chief of “let’s actually race clean”'],
    sponsors: ["Teal Line Dynamics", "Coral Grip"],
    lines: ["Clean beats loud.", "Hold the line."],
    rival: "Dale (friendly family heat)",
    careerWins: 1,
    stats: {
      driving: 72,
      speed: 68,
      handling: 76,
      consistency: 78,
      aggression: 48,
      luck: 80,
    },
    accent: "#2dd4bf",
  },
  {
    id: "abby",
    name: "Abby",
    nickname: "Apex",
    number: "12",
    slug: "abby",
    image: "/drivers/abby.png",
    tagline: "Late brake. Early grin.",
    bio: "Abby races like the track was drawn for her. Sharp entries, cleaner exits, and a habit of making hard sections look easy.",
    catchphrase: "Late brake. Early grin.",
    signature: "Needle Thread through the slalom",
    strength: "Precision gates",
    funFact: "Names cup layouts after emotions (“this one’s spicy”).",
    credentials: ["Slalom specialist on paper and in spirit"],
    sponsors: ["Teal Line Dynamics", "Needle Thread Racing"],
    lines: ["Spicy chicane incoming.", "Thread it."],
    rival: "Logan",
    careerWins: 1,
    stats: {
      driving: 70,
      speed: 72,
      handling: 77,
      consistency: 75,
      aggression: 54,
      luck: 70,
    },
    accent: "#14b8a6",
  },
  {
    id: "mary",
    name: "Mary",
    nickname: "Mirage",
    number: "05",
    slug: "mary",
    image: "/drivers/mary.png",
    tagline: "No rush. Just results.",
    bio: "Mary’s pace shows up like heat shimmer on the road — you don’t always see it coming, then she’s somehow ahead and somehow serene about it.",
    catchphrase: "No rush. Just results.",
    signature: "Heat Haze Pass",
    strength: "Composure + clean craft",
    funFact: "Never admits she was trying that hard.",
    credentials: ["Smooth operator", "Soft voice, sharp laps"],
    sponsors: ["Horizon Calm Racing"],
    lines: ["Heat haze.", "Still ahead."],
    rival: "Whoever underestimates her",
    careerWins: 1,
    stats: {
      driving: 68,
      speed: 70,
      handling: 80,
      consistency: 82,
      aggression: 40,
      luck: 85,
    },
    accent: "#f0abfc",
  },
  {
    id: "maddie",
    name: "Maddie",
    nickname: "Mayhem",
    number: "18",
    slug: "maddie",
    image: "/drivers/maddie.png",
    tagline: "Wide open, wider smile.",
    bio: "Full send, full heart, full entertainment. Maddie turns every heat into appointment viewing — and somehow still looks cool doing it.",
    catchphrase: "Wide open, wider smile.",
    signature: "Party Mode — maximum attack from lap one",
    strength: "Pure pace energy",
    funFact: "Mini-prize gravity well — they just find her.",
    credentials: ["Chaos, but charismatic chaos", "Best imaginary onboards"],
    sponsors: ["Party Mode Athletics", "Flamingo Fuel"],
    lines: ["Cones are red suggestions.", "Send it."],
    rival: "The entire cup layout",
    careerWins: 0,
    stats: {
      driving: 65,
      speed: 90,
      handling: 50,
      consistency: 40,
      aggression: 95,
      luck: 88,
    },
    accent: "#f43f5e",
  },
  {
    id: "dale",
    name: "Dale",
    nickname: "Daily Driver",
    number: "88",
    slug: "dale",
    image: "/drivers/dale.png",
    tagline: "We’re already winning — we’re here.",
    bio: "Dale’s here for the joy of it — the cars, the cups, the crew, the whole circus. The stats are humble; the heart is maxed out. Every grid needs a good sport who keeps the weekend fun.",
    catchphrase: "We’re already winning — we’re here.",
    signature: "Participation Apex (said with pride)",
    strength: "Morale · Endless encouragement",
    funFact: "First to cheer when someone else wins a mini-prize.",
    credentials: ["Chief Vibes Officer", "Official hug backup for Grammy’s victory laps"],
    sponsors: ["Good Sport Garage", "Beach Blanket Racing"],
    lines: [
      "Someone’s gotta make the rest of you look legendary.",
      "Cheer loud. Race happy.",
    ],
    rival: "The leaderboard (friendly rivalry)",
    careerWins: 0,
    stats: {
      driving: 42,
      speed: 40,
      handling: 38,
      consistency: 35,
      aggression: 30,
      luck: 45,
    },
    accent: "#94a3b8",
  },
];

export function getDriver(slug: string) {
  return DRIVERS.find((d) => d.slug === slug);
}

export function shuffleDrivers(list: Driver[] = DRIVERS) {
  const copy = [...list];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}
